/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'roleplay' : IDL.Null,
  'simulator' : IDL.Null,
  'adventure' : IDL.Null,
});
export const Experience = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'thumbsDown' : IDL.Nat,
  'playerCount' : IDL.Nat,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'thumbsUp' : IDL.Nat,
  'category' : Category,
  'gameplayControls' : IDL.Text,
});
export const DiniVerseUser = IDL.Record({
  'displayName' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});
export const FriendRequestStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const FriendRequest = IDL.Record({
  'to' : IDL.Principal,
  'status' : FriendRequestStatus,
  'from' : IDL.Principal,
});
export const MessageInput = IDL.Record({
  'content' : IDL.Text,
  'receiver' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExperience' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), Category, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(DiniVerseUser)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(DiniVerseUser)], ['query']),
  'getExperience' : IDL.Func([IDL.Text], [IDL.Opt(Experience)], ['query']),
  'getExperiencesByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getExperiencesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getFriendsList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getGameplayControls' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getPendingFriendRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getTrendingExperiences' : IDL.Func(
      [Category],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DiniVerseUser)],
      ['query'],
    ),
  'incrementPlayerCount' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rateExperience' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'respondToFriendRequest' : IDL.Func(
      [
        IDL.Principal,
        IDL.Variant({ 'accept' : IDL.Null, 'decline' : IDL.Null }),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([DiniVerseUser], [], []),
  'searchExperiences' : IDL.Func([IDL.Text], [IDL.Vec(Experience)], ['query']),
  'searchUsersByDisplayName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, DiniVerseUser))],
      ['query'],
    ),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [FriendRequest], []),
  'sendMessage' : IDL.Func([MessageInput], [Message], []),
  'signUp' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'unfriend' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'roleplay' : IDL.Null,
    'simulator' : IDL.Null,
    'adventure' : IDL.Null,
  });
  const Experience = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'thumbsDown' : IDL.Nat,
    'playerCount' : IDL.Nat,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'thumbsUp' : IDL.Nat,
    'category' : Category,
    'gameplayControls' : IDL.Text,
  });
  const DiniVerseUser = IDL.Record({
    'displayName' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  const FriendRequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const FriendRequest = IDL.Record({
    'to' : IDL.Principal,
    'status' : FriendRequestStatus,
    'from' : IDL.Principal,
  });
  const MessageInput = IDL.Record({
    'content' : IDL.Text,
    'receiver' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExperience' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), Category, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(DiniVerseUser)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(DiniVerseUser)], ['query']),
    'getExperience' : IDL.Func([IDL.Text], [IDL.Opt(Experience)], ['query']),
    'getExperiencesByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getExperiencesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getFriendsList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getGameplayControls' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getPendingFriendRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getTrendingExperiences' : IDL.Func(
        [Category],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DiniVerseUser)],
        ['query'],
      ),
    'incrementPlayerCount' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rateExperience' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'respondToFriendRequest' : IDL.Func(
        [
          IDL.Principal,
          IDL.Variant({ 'accept' : IDL.Null, 'decline' : IDL.Null }),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([DiniVerseUser], [], []),
    'searchExperiences' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'searchUsersByDisplayName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, DiniVerseUser))],
        ['query'],
      ),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [FriendRequest], []),
    'sendMessage' : IDL.Func([MessageInput], [Message], []),
    'signUp' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'unfriend' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };