/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'roleplay' : IDL.Null,
  'simulator' : IDL.Null,
  'adventure' : IDL.Null,
});
export const Experience = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'thumbsDown' : IDL.Nat,
  'playerCount' : IDL.Nat,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'thumbsUp' : IDL.Nat,
  'category' : Category,
  'gameplayControls' : IDL.Text,
});
export const Language = IDL.Variant({
  'de' : IDL.Null,
  'en' : IDL.Null,
  'es' : IDL.Null,
  'fr' : IDL.Null,
  'ko' : IDL.Null,
  'nl' : IDL.Null,
  'pt' : IDL.Null,
  'ru' : IDL.Null,
  'tr' : IDL.Null,
  'vi' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const TextDirection = IDL.Variant({
  'leftToRight' : IDL.Null,
  'rightToLeft' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'languageCode' : IDL.Text,
  'language' : Language,
  'gender' : Gender,
  'languagePrefix' : IDL.Text,
  'textDirection' : TextDirection,
  'visibility' : IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
  'nativeLanguage' : Language,
  'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const Time = IDL.Int;
export const UserSettings = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'lastDisplayNameChange' : Time,
  'languageCode' : IDL.Text,
  'language' : Language,
  'passwordResetAttempts' : IDL.Nat,
  'updatedAt' : Time,
  'lastPasswordChange' : Time,
  'gender' : Gender,
  'pronunciationLanguage' : Language,
  'languagePrefix' : IDL.Text,
  'textDirection' : TextDirection,
  'visibility' : IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
  'lastUsernameChange' : Time,
  'nativeLanguage' : Language,
  'lastPasswordResetAttempt' : Time,
  'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});

export const idlService = IDL.Service({
  'deleteAccount' : IDL.Func([], [], []),
  'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getExperiencesByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getExperiencesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'getTrendingExperiences' : IDL.Func(
      [Category],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'searchExperiences' : IDL.Func([IDL.Text], [IDL.Vec(Experience)], ['query']),
  'setGender' : IDL.Func([Gender], [], []),
  'setLanguage' : IDL.Func(
      [Language, IDL.Text, IDL.Text, TextDirection, Language],
      [],
      [],
    ),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateVisibility' : IDL.Func(
      [IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null })],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'roleplay' : IDL.Null,
    'simulator' : IDL.Null,
    'adventure' : IDL.Null,
  });
  const Experience = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'thumbsDown' : IDL.Nat,
    'playerCount' : IDL.Nat,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'thumbsUp' : IDL.Nat,
    'category' : Category,
    'gameplayControls' : IDL.Text,
  });
  const Language = IDL.Variant({
    'de' : IDL.Null,
    'en' : IDL.Null,
    'es' : IDL.Null,
    'fr' : IDL.Null,
    'ko' : IDL.Null,
    'nl' : IDL.Null,
    'pt' : IDL.Null,
    'ru' : IDL.Null,
    'tr' : IDL.Null,
    'vi' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const TextDirection = IDL.Variant({
    'leftToRight' : IDL.Null,
    'rightToLeft' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'languageCode' : IDL.Text,
    'language' : Language,
    'gender' : Gender,
    'languagePrefix' : IDL.Text,
    'textDirection' : TextDirection,
    'visibility' : IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
    'nativeLanguage' : Language,
    'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const Time = IDL.Int;
  const UserSettings = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'lastDisplayNameChange' : Time,
    'languageCode' : IDL.Text,
    'language' : Language,
    'passwordResetAttempts' : IDL.Nat,
    'updatedAt' : Time,
    'lastPasswordChange' : Time,
    'gender' : Gender,
    'pronunciationLanguage' : Language,
    'languagePrefix' : IDL.Text,
    'textDirection' : TextDirection,
    'visibility' : IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
    'lastUsernameChange' : Time,
    'nativeLanguage' : Language,
    'lastPasswordResetAttempt' : Time,
    'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  
  return IDL.Service({
    'deleteAccount' : IDL.Func([], [], []),
    'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getExperiencesByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getExperiencesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getTrendingExperiences' : IDL.Func(
        [Category],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'searchExperiences' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'setGender' : IDL.Func([Gender], [], []),
    'setLanguage' : IDL.Func(
        [Language, IDL.Text, IDL.Text, TextDirection, Language],
        [],
        [],
      ),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateVisibility' : IDL.Func(
        [IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null })],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };