/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'roleplay' : null } |
  { 'simulator' : null } |
  { 'adventure' : null };
export interface Experience {
  'id' : string,
  'title' : string,
  'thumbnail' : [] | [Uint8Array],
  'thumbsDown' : bigint,
  'playerCount' : bigint,
  'description' : string,
  'author' : Principal,
  'thumbsUp' : bigint,
  'category' : Category,
  'gameplayControls' : string,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type Language = { 'de' : null } |
  { 'en' : null } |
  { 'es' : null } |
  { 'fr' : null } |
  { 'ko' : null } |
  { 'nl' : null } |
  { 'pt' : null } |
  { 'ru' : null } |
  { 'tr' : null } |
  { 'vi' : null };
export type TextDirection = { 'leftToRight' : null } |
  { 'rightToLeft' : null };
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'languageCode' : string,
  'language' : Language,
  'gender' : Gender,
  'languagePrefix' : string,
  'textDirection' : TextDirection,
  'visibility' : { 'offline' : null } |
    { 'online' : null },
  'nativeLanguage' : Language,
  'avatar' : [] | [Uint8Array],
}
export interface UserSettings {
  'username' : string,
  'displayName' : string,
  'createdAt' : Time,
  'lastDisplayNameChange' : Time,
  'languageCode' : string,
  'language' : Language,
  'passwordResetAttempts' : bigint,
  'updatedAt' : Time,
  'lastPasswordChange' : Time,
  'gender' : Gender,
  'pronunciationLanguage' : Language,
  'languagePrefix' : string,
  'textDirection' : TextDirection,
  'visibility' : { 'offline' : null } |
    { 'online' : null },
  'lastUsernameChange' : Time,
  'nativeLanguage' : Language,
  'lastPasswordResetAttempt' : Time,
  'avatar' : [] | [Uint8Array],
}
export interface _SERVICE {
  'deleteAccount' : ActorMethod<[], undefined>,
  'getAllExperiences' : ActorMethod<[], Array<Experience>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getExperiencesByAuthor' : ActorMethod<[Principal], Array<Experience>>,
  'getExperiencesByCategory' : ActorMethod<[Category], Array<Experience>>,
  'getSettings' : ActorMethod<[], UserSettings>,
  'getTrendingExperiences' : ActorMethod<[Category], Array<Experience>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'searchExperiences' : ActorMethod<[string], Array<Experience>>,
  'setGender' : ActorMethod<[Gender], undefined>,
  'setLanguage' : ActorMethod<
    [Language, string, string, TextDirection, Language],
    undefined
  >,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'updateVisibility' : ActorMethod<
    [{ 'offline' : null } | { 'online' : null }],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];