/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Experience {
    id: string;
    title: string;
    thumbnail?: ExternalBlob;
    thumbsDown: bigint;
    playerCount: bigint;
    description: string;
    author: Principal;
    thumbsUp: bigint;
    category: Category;
    gameplayControls: string;
}
export interface UserSettings {
    username: string;
    displayName: string;
    createdAt: Time;
    lastDisplayNameChange: Time;
    languageCode: string;
    language: Language;
    passwordResetAttempts: bigint;
    updatedAt: Time;
    lastPasswordChange: Time;
    gender: Gender;
    pronunciationLanguage: Language;
    languagePrefix: string;
    textDirection: TextDirection;
    visibility: Variant_offline_online;
    lastUsernameChange: Time;
    nativeLanguage: Language;
    lastPasswordResetAttempt: Time;
    avatar?: ExternalBlob;
}
export interface UserProfile {
    displayName: string;
    languageCode: string;
    language: Language;
    gender: Gender;
    languagePrefix: string;
    textDirection: TextDirection;
    visibility: Variant_offline_online;
    nativeLanguage: Language;
    avatar?: ExternalBlob;
}
export enum Category {
    roleplay = "roleplay",
    simulator = "simulator",
    adventure = "adventure"
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum Language {
    de = "de",
    en = "en",
    es = "es",
    fr = "fr",
    ko = "ko",
    nl = "nl",
    pt = "pt",
    ru = "ru",
    tr = "tr",
    vi = "vi"
}
export enum TextDirection {
    leftToRight = "leftToRight",
    rightToLeft = "rightToLeft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_offline_online {
    offline = "offline",
    online = "online"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAccount(): Promise<void>;
    deleteAvatar(): Promise<void>;
    getAllExperiences(): Promise<Array<Experience>>;
    getAllLanguageSettings(): Promise<Array<[Principal, UserSettings]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExperiencesByAuthor(author: Principal): Promise<Array<Experience>>;
    getExperiencesByCategory(category: Category): Promise<Array<Experience>>;
    getGender(): Promise<Gender>;
    getLanguageSettings(): Promise<[Language, string, string, TextDirection, Language]>;
    getSettings(): Promise<UserSettings>;
    getTrendingExperiences(category: Category): Promise<Array<Experience>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(displayName: string, avatar: ExternalBlob | null, visibility: Variant_offline_online, gender: Gender, language: Language, languageCode: string, languagePrefix: string, textDirection: TextDirection, nativeLanguage: Language): Promise<void>;
    searchExperiences(searchTerm: string): Promise<Array<Experience>>;
    setGender(gender: Gender): Promise<void>;
    setLanguage(language: Language, languageCode: string, languagePrefix: string, textDirection: TextDirection, nativeLanguage: Language): Promise<void>;
    updateDisplayName(newDisplayName: string): Promise<void>;
    updateDisplayNameAndAvatar(newDisplayName: string, avatar: ExternalBlob | null): Promise<void>;
    updateVisibility(visibility: Visibility): Promise<void>;
}
import type { Category as _Category, Experience as _Experience, ExternalBlob as _ExternalBlob, Gender as _Gender, Language as _Language, TextDirection as _TextDirection, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserSettings as _UserSettings, Visibility as _Visibility, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAccount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount();
            return result;
        }
    }
    async deleteAvatar(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAvatar();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAvatar();
            return result;
        }
    }
    async getAllExperiences(): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExperiences();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExperiences();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLanguageSettings(): Promise<Array<[Principal, UserSettings]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLanguageSettings();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLanguageSettings();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExperiencesByAuthor(arg0: Principal): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperiencesByAuthor(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperiencesByAuthor(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExperiencesByCategory(arg0: Category): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperiencesByCategory(to_candid_Category_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperiencesByCategory(to_candid_Category_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGender(): Promise<Gender> {
        if (this.processError) {
            try {
                const result = await this.actor.getGender();
                return from_candid_Gender_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGender();
            return from_candid_Gender_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLanguageSettings(): Promise<[Language, string, string, TextDirection, Language]> {
        if (this.processError) {
            try {
                const result = await this.actor.getLanguageSettings();
                return [
                    from_candid_Language_n21(this._uploadFile, this._downloadFile, result[0]),
                    result[1],
                    result[2],
                    from_candid_TextDirection_n25(this._uploadFile, this._downloadFile, result[3]),
                    from_candid_Language_n21(this._uploadFile, this._downloadFile, result[4])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLanguageSettings();
            return [
                from_candid_Language_n21(this._uploadFile, this._downloadFile, result[0]),
                result[1],
                result[2],
                from_candid_TextDirection_n25(this._uploadFile, this._downloadFile, result[3]),
                from_candid_Language_n21(this._uploadFile, this._downloadFile, result[4])
            ];
        }
    }
    async getSettings(): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_UserSettings_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_UserSettings_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingExperiences(arg0: Category): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingExperiences(to_candid_Category_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingExperiences(to_candid_Category_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: ExternalBlob | null, arg2: Variant_offline_online, arg3: Gender, arg4: Language, arg5: string, arg6: string, arg7: TextDirection, arg8: Language): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, await to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1), to_candid_variant_n37(this._uploadFile, this._downloadFile, arg2), to_candid_Gender_n38(this._uploadFile, this._downloadFile, arg3), to_candid_Language_n40(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_TextDirection_n42(this._uploadFile, this._downloadFile, arg7), to_candid_Language_n40(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, await to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1), to_candid_variant_n37(this._uploadFile, this._downloadFile, arg2), to_candid_Gender_n38(this._uploadFile, this._downloadFile, arg3), to_candid_Language_n40(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_TextDirection_n42(this._uploadFile, this._downloadFile, arg7), to_candid_Language_n40(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async searchExperiences(arg0: string): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchExperiences(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchExperiences(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setGender(arg0: Gender): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGender(to_candid_Gender_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGender(to_candid_Gender_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setLanguage(arg0: Language, arg1: string, arg2: string, arg3: TextDirection, arg4: Language): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLanguage(to_candid_Language_n40(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_TextDirection_n42(this._uploadFile, this._downloadFile, arg3), to_candid_Language_n40(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLanguage(to_candid_Language_n40(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_TextDirection_n42(this._uploadFile, this._downloadFile, arg3), to_candid_Language_n40(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayName(arg0);
            return result;
        }
    }
    async updateDisplayNameAndAvatar(arg0: string, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayNameAndAvatar(arg0, await to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayNameAndAvatar(arg0, await to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVisibility(arg0: Visibility): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisibility(to_candid_Visibility_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisibility(to_candid_Visibility_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Category_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_Experience_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Experience): Promise<Experience> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TextDirection_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TextDirection): TextDirection {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_UserSettings_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettings): Promise<UserSettings> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    thumbnail: [] | [_ExternalBlob];
    thumbsDown: bigint;
    playerCount: bigint;
    description: string;
    author: Principal;
    thumbsUp: bigint;
    category: _Category;
    gameplayControls: string;
}): Promise<{
    id: string;
    title: string;
    thumbnail?: ExternalBlob;
    thumbsDown: bigint;
    playerCount: bigint;
    description: string;
    author: Principal;
    thumbsUp: bigint;
    category: Category;
    gameplayControls: string;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.thumbnail)),
        thumbsDown: value.thumbsDown,
        playerCount: value.playerCount,
        description: value.description,
        author: value.author,
        thumbsUp: value.thumbsUp,
        category: from_candid_Category_n15(_uploadFile, _downloadFile, value.category),
        gameplayControls: value.gameplayControls
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    createdAt: _Time;
    lastDisplayNameChange: _Time;
    languageCode: string;
    language: _Language;
    passwordResetAttempts: bigint;
    updatedAt: _Time;
    lastPasswordChange: _Time;
    gender: _Gender;
    pronunciationLanguage: _Language;
    languagePrefix: string;
    textDirection: _TextDirection;
    visibility: {
        offline: null;
    } | {
        online: null;
    };
    lastUsernameChange: _Time;
    nativeLanguage: _Language;
    lastPasswordResetAttempt: _Time;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    username: string;
    displayName: string;
    createdAt: Time;
    lastDisplayNameChange: Time;
    languageCode: string;
    language: Language;
    passwordResetAttempts: bigint;
    updatedAt: Time;
    lastPasswordChange: Time;
    gender: Gender;
    pronunciationLanguage: Language;
    languagePrefix: string;
    textDirection: TextDirection;
    visibility: Variant_offline_online;
    lastUsernameChange: Time;
    nativeLanguage: Language;
    lastPasswordResetAttempt: Time;
    avatar?: ExternalBlob;
}> {
    return {
        username: value.username,
        displayName: value.displayName,
        createdAt: value.createdAt,
        lastDisplayNameChange: value.lastDisplayNameChange,
        languageCode: value.languageCode,
        language: from_candid_Language_n21(_uploadFile, _downloadFile, value.language),
        passwordResetAttempts: value.passwordResetAttempts,
        updatedAt: value.updatedAt,
        lastPasswordChange: value.lastPasswordChange,
        gender: from_candid_Gender_n23(_uploadFile, _downloadFile, value.gender),
        pronunciationLanguage: from_candid_Language_n21(_uploadFile, _downloadFile, value.pronunciationLanguage),
        languagePrefix: value.languagePrefix,
        textDirection: from_candid_TextDirection_n25(_uploadFile, _downloadFile, value.textDirection),
        visibility: from_candid_variant_n27(_uploadFile, _downloadFile, value.visibility),
        lastUsernameChange: value.lastUsernameChange,
        nativeLanguage: from_candid_Language_n21(_uploadFile, _downloadFile, value.nativeLanguage),
        lastPasswordResetAttempt: value.lastPasswordResetAttempt,
        avatar: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    languageCode: string;
    language: _Language;
    gender: _Gender;
    languagePrefix: string;
    textDirection: _TextDirection;
    visibility: {
        offline: null;
    } | {
        online: null;
    };
    nativeLanguage: _Language;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    displayName: string;
    languageCode: string;
    language: Language;
    gender: Gender;
    languagePrefix: string;
    textDirection: TextDirection;
    visibility: Variant_offline_online;
    nativeLanguage: Language;
    avatar?: ExternalBlob;
}> {
    return {
        displayName: value.displayName,
        languageCode: value.languageCode,
        language: from_candid_Language_n21(_uploadFile, _downloadFile, value.language),
        gender: from_candid_Gender_n23(_uploadFile, _downloadFile, value.gender),
        languagePrefix: value.languagePrefix,
        textDirection: from_candid_TextDirection_n25(_uploadFile, _downloadFile, value.textDirection),
        visibility: from_candid_variant_n27(_uploadFile, _downloadFile, value.visibility),
        nativeLanguage: from_candid_Language_n21(_uploadFile, _downloadFile, value.nativeLanguage),
        avatar: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserSettings]): Promise<[Principal, UserSettings]> {
    return [
        value[0],
        await from_candid_UserSettings_n19(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roleplay: null;
} | {
    simulator: null;
} | {
    adventure: null;
}): Category {
    return "roleplay" in value ? Category.roleplay : "simulator" in value ? Category.simulator : "adventure" in value ? Category.adventure : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    de: null;
} | {
    en: null;
} | {
    es: null;
} | {
    fr: null;
} | {
    ko: null;
} | {
    nl: null;
} | {
    pt: null;
} | {
    ru: null;
} | {
    tr: null;
} | {
    vi: null;
}): Language {
    return "de" in value ? Language.de : "en" in value ? Language.en : "es" in value ? Language.es : "fr" in value ? Language.fr : "ko" in value ? Language.ko : "nl" in value ? Language.nl : "pt" in value ? Language.pt : "ru" in value ? Language.ru : "tr" in value ? Language.tr : "vi" in value ? Language.vi : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leftToRight: null;
} | {
    rightToLeft: null;
}): TextDirection {
    return "leftToRight" in value ? TextDirection.leftToRight : "rightToLeft" in value ? TextDirection.rightToLeft : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offline: null;
} | {
    online: null;
}): Variant_offline_online {
    return "offline" in value ? Variant_offline_online.offline : "online" in value ? Variant_offline_online.online : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Experience>): Promise<Array<Experience>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Experience_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserSettings]>): Promise<Array<[Principal, UserSettings]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n18(_uploadFile, _downloadFile, x)));
}
function to_candid_Category_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_TextDirection_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextDirection): _TextDirection {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Visibility_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visibility): _Visibility {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    roleplay: null;
} | {
    simulator: null;
} | {
    adventure: null;
} {
    return value == Category.roleplay ? {
        roleplay: null
    } : value == Category.simulator ? {
        simulator: null
    } : value == Category.adventure ? {
        adventure: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_offline_online): {
    offline: null;
} | {
    online: null;
} {
    return value == Variant_offline_online.offline ? {
        offline: null
    } : value == Variant_offline_online.online ? {
        online: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    de: null;
} | {
    en: null;
} | {
    es: null;
} | {
    fr: null;
} | {
    ko: null;
} | {
    nl: null;
} | {
    pt: null;
} | {
    ru: null;
} | {
    tr: null;
} | {
    vi: null;
} {
    return value == Language.de ? {
        de: null
    } : value == Language.en ? {
        en: null
    } : value == Language.es ? {
        es: null
    } : value == Language.fr ? {
        fr: null
    } : value == Language.ko ? {
        ko: null
    } : value == Language.nl ? {
        nl: null
    } : value == Language.pt ? {
        pt: null
    } : value == Language.ru ? {
        ru: null
    } : value == Language.tr ? {
        tr: null
    } : value == Language.vi ? {
        vi: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextDirection): {
    leftToRight: null;
} | {
    rightToLeft: null;
} {
    return value == TextDirection.leftToRight ? {
        leftToRight: null
    } : value == TextDirection.rightToLeft ? {
        rightToLeft: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
