/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'roleplay' : IDL.Null,
  'simulator' : IDL.Null,
  'adventure' : IDL.Null,
});
export const Experience = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'thumbsDown' : IDL.Nat,
  'playerCount' : IDL.Nat,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'thumbsUp' : IDL.Nat,
  'category' : Category,
  'gameplayControls' : IDL.Text,
});
export const Time = IDL.Int;
export const Language = IDL.Variant({
  'de' : IDL.Null,
  'en' : IDL.Null,
  'es' : IDL.Null,
  'fr' : IDL.Null,
  'ko' : IDL.Null,
  'nl' : IDL.Null,
  'pt' : IDL.Null,
  'ru' : IDL.Null,
  'tr' : IDL.Null,
  'vi' : IDL.Null,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const TextDirection = IDL.Variant({
  'leftToRight' : IDL.Null,
  'rightToLeft' : IDL.Null,
});
export const UserSettings = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'lastDisplayNameChange' : Time,
  'languageCode' : IDL.Text,
  'language' : Language,
  'passwordResetAttempts' : IDL.Nat,
  'updatedAt' : Time,
  'lastPasswordChange' : Time,
  'gender' : Gender,
  'pronunciationLanguage' : Language,
  'languagePrefix' : IDL.Text,
  'textDirection' : TextDirection,
  'visibility' : IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
  'lastUsernameChange' : Time,
  'nativeLanguage' : Language,
  'lastPasswordResetAttempt' : Time,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'languageCode' : IDL.Text,
  'language' : Language,
  'gender' : Gender,
  'languagePrefix' : IDL.Text,
  'textDirection' : TextDirection,
  'visibility' : IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
  'nativeLanguage' : Language,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Visibility = IDL.Variant({
  'offline' : IDL.Null,
  'online' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteAvatar' : IDL.Func([], [], []),
  'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getAllLanguageSettings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserSettings))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExperiencesByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getExperiencesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getGender' : IDL.Func([], [Gender], ['query']),
  'getLanguageSettings' : IDL.Func(
      [],
      [Language, IDL.Text, IDL.Text, TextDirection, Language],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'getTrendingExperiences' : IDL.Func(
      [Category],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
        Gender,
        Language,
        IDL.Text,
        IDL.Text,
        TextDirection,
        Language,
      ],
      [],
      [],
    ),
  'searchExperiences' : IDL.Func([IDL.Text], [IDL.Vec(Experience)], ['query']),
  'setGender' : IDL.Func([Gender], [], []),
  'setLanguage' : IDL.Func(
      [Language, IDL.Text, IDL.Text, TextDirection, Language],
      [],
      [],
    ),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateDisplayNameAndAvatar' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateVisibility' : IDL.Func([Visibility], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'roleplay' : IDL.Null,
    'simulator' : IDL.Null,
    'adventure' : IDL.Null,
  });
  const Experience = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'thumbsDown' : IDL.Nat,
    'playerCount' : IDL.Nat,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'thumbsUp' : IDL.Nat,
    'category' : Category,
    'gameplayControls' : IDL.Text,
  });
  const Time = IDL.Int;
  const Language = IDL.Variant({
    'de' : IDL.Null,
    'en' : IDL.Null,
    'es' : IDL.Null,
    'fr' : IDL.Null,
    'ko' : IDL.Null,
    'nl' : IDL.Null,
    'pt' : IDL.Null,
    'ru' : IDL.Null,
    'tr' : IDL.Null,
    'vi' : IDL.Null,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const TextDirection = IDL.Variant({
    'leftToRight' : IDL.Null,
    'rightToLeft' : IDL.Null,
  });
  const UserSettings = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'lastDisplayNameChange' : Time,
    'languageCode' : IDL.Text,
    'language' : Language,
    'passwordResetAttempts' : IDL.Nat,
    'updatedAt' : Time,
    'lastPasswordChange' : Time,
    'gender' : Gender,
    'pronunciationLanguage' : Language,
    'languagePrefix' : IDL.Text,
    'textDirection' : TextDirection,
    'visibility' : IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
    'lastUsernameChange' : Time,
    'nativeLanguage' : Language,
    'lastPasswordResetAttempt' : Time,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'languageCode' : IDL.Text,
    'language' : Language,
    'gender' : Gender,
    'languagePrefix' : IDL.Text,
    'textDirection' : TextDirection,
    'visibility' : IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
    'nativeLanguage' : Language,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Visibility = IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteAvatar' : IDL.Func([], [], []),
    'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getAllLanguageSettings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserSettings))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExperiencesByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getExperiencesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getGender' : IDL.Func([], [Gender], ['query']),
    'getLanguageSettings' : IDL.Func(
        [],
        [Language, IDL.Text, IDL.Text, TextDirection, Language],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getTrendingExperiences' : IDL.Func(
        [Category],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null }),
          Gender,
          Language,
          IDL.Text,
          IDL.Text,
          TextDirection,
          Language,
        ],
        [],
        [],
      ),
    'searchExperiences' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'setGender' : IDL.Func([Gender], [], []),
    'setLanguage' : IDL.Func(
        [Language, IDL.Text, IDL.Text, TextDirection, Language],
        [],
        [],
      ),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateDisplayNameAndAvatar' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateVisibility' : IDL.Func([Visibility], [], []),
  });
};

export const init = ({ IDL }) => { return []; };